### ISSUE TITLE
Is main branch protected?

### ISSUE THREAD

**Issue by barrymoore1990** [cristianmitu/ProjectOne#1]
Says to protect the main branch so we can't upload to it in repo settings - can't check from my end

Minute 2 of video - https://zoom.us/rec/play/n4j5oBxtFNa8KFSkR9Yb4GStFVWDVVGruEnSVvHej1IcgNl0F6P1xAeGJNtvlmyPgjdOT8VCsqsBNQs0.rTqFRfUZobJzlCBF?startTime=1675260629000&_x_zm_rtaid=09dJG6XIRGuock0ggXHM3w.1675346453508.18b8523d716291d9c32c6fe40d7d769a&_x_zm_rhtaid=359

**Comment by cristianmitu** [comment]
It's not protected Barry , I created another repository and I added you and Chindi there , we will talk tomorrow , hope everything is fine . See you tomorrow!
    On Thursday, February 2, 2023 at 02:26:00 PM GMT, barrymoore1990 ***@***.***> wrote:  
 
 


Minute 2 of video - https://zoom.us/rec/play/n4j5oBxtFNa8KFSkR9Yb4GStFVWDVVGruEnSVvHej1IcgNl0F6P1xAeGJNtvlmyPgjdOT8VCsqsBNQs0.rTqFRfUZobJzlCBF?startTime=1675260629000&_x_zm_rtaid=09dJG6XIRGuock0ggXHM3w.1675346453508.18b8523d716291d9c32c6fe40d7d769a&_x_zm_rhtaid=359

Says to protect the main branch so we can't upload to it

**Comment by barrymoore1990** [comment]
Complete
